import bs                           #Created By MythB # http://github.com/MythB
import bsInternal
import os

chatfile = '/root/bs/chat/ChatMessages.html'
#Use your own file location here
class RSSchat(object):

    def collector(self,nick,msg):
        #get account id from nick
        """for i in bsInternal._getForegroundHostSession().players:#FIX ME
            if i.getName().encode('utf-8') == nick: # use i.getName(True) if you need fullname
               accountID = i.get_account_id()
            else:
               accountID = 'NOT RESOLVED'"""
        #get the current time
        msgTime = ''
        from datetime import datetime
        msgTime = datetime.now().strftime('%d-%m-%Y %H:%M:%S')

        #generate a pretty html log table (ignore errors it's fine)
        if not os.path.exists(chatfile):
            with open(chatfile,mode='w') as f:
                f.write("""<!DOCTYPE html><head><meta charset="UTF-8"></head><body><p><b>Automatically generated by <a href="http://bombsquadgame.com ">
                        BombSquad</a> Server - Created by <a href="http://github.com/MythB ">MythB</a> - """ +msgTime+ """
                        </b></p><style>table,th,td {border: 0.1px solid grey;}</style><table style="width:100%"><tr>
                        <th align="left">NAME</th><th align="left">MESSAGE</th><th align="left">DATE</th></tr>""")           
        else:
            with open(chatfile,mode='a') as f:
                f.write('<tr><td>'+nick+'</td><td>'+msg+'</td><td>'+msgTime+'</td></tr>')
t=RSSchat()
def collectedMsg(msg):
    if bsInternal._getForegroundHostActivity() is not None:
        m = msg.split(': ')
        t.collector(m[0],m[1])    
